name: release-drafter

on:
  push:
    # trigger on tags and release branches only
    branches:
      - release-*
    tags:
      - v*

  workflow_dispatch:

jobs:
  update_release_draft:
    uses: nvidia-merlin/.github/.github/workflows/release-drafter-common.yaml@main
